import Link from 'next/link'
import { BookOpen, Brain, FileText, Sparkles } from 'lucide-react'
import TrialCounter from '@/components/layout/TrialCounter'

export default function HomePage() {
  return (
    <div className="container-custom py-12">
      {/* Hero Section */}
      <section className="text-center mb-16">
        <div className="mb-8">
          <TrialCounter />
        </div>

        <h1 className="text-5xl md:text-6xl font-bold mb-6 text-gradient">
          Master English with AI
        </h1>

        <p className="text-xl md:text-2xl text-gray-300 mb-8 max-w-3xl mx-auto">
          Unlimited AI-generated exercises for A1-B2 levels.
          Instant grading, downloadable PDFs, and personalized learning.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link href="/levels" className="btn-primary">
            Start Learning Now
          </Link>
          <Link
            href="/subscribe"
            className="px-10 py-4 text-lg font-semibold text-white rounded-[10px] border-2 border-purple-500 hover:bg-purple-500/10 transition-all duration-300"
          >
            View Plans
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="grid md:grid-cols-3 gap-8 mb-16">
        <div className="card text-center">
          <div className="flex justify-center mb-4">
            <div className="gradient-purple p-4 rounded-full">
              <Brain className="w-8 h-8 text-white" />
            </div>
          </div>
          <h3 className="mb-3">Grammar Exercises</h3>
          <p className="text-gray-400">
            20-question tests with instant grading and detailed explanations. Perfect for mastering English grammar.
          </p>
        </div>

        <div className="card text-center">
          <div className="flex justify-center mb-4">
            <div className="gradient-purple p-4 rounded-full">
              <BookOpen className="w-8 h-8 text-white" />
            </div>
          </div>
          <h3 className="mb-3">Vocabulary Building</h3>
          <p className="text-gray-400">
            Interactive flashcards and exercises to expand your English vocabulary at every level.
          </p>
        </div>

        <div className="card text-center">
          <div className="flex justify-center mb-4">
            <div className="gradient-purple p-4 rounded-full">
              <FileText className="w-8 h-8 text-white" />
            </div>
          </div>
          <h3 className="mb-3">Reading Practice</h3>
          <p className="text-gray-400">
            Level-appropriate paragraphs generated by AI for reading comprehension practice.
          </p>
        </div>
      </section>

      {/* How It Works */}
      <section className="card mb-16">
        <h2 className="text-center mb-8 text-gradient">How It Works</h2>

        <div className="grid md:grid-cols-4 gap-6">
          <div className="text-center">
            <div className="gradient-pink w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4 text-white font-bold text-xl">
              1
            </div>
            <h4 className="font-semibold mb-2">Choose Your Level</h4>
            <p className="text-sm text-gray-400">Select from A1, A2, B1, or B2</p>
          </div>

          <div className="text-center">
            <div className="gradient-pink w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4 text-white font-bold text-xl">
              2
            </div>
            <h4 className="font-semibold mb-2">Pick a Category</h4>
            <p className="text-sm text-gray-400">Grammar, Vocabulary, or Paragraphs</p>
          </div>

          <div className="text-center">
            <div className="gradient-pink w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4 text-white font-bold text-xl">
              3
            </div>
            <h4 className="font-semibold mb-2">Practice & Learn</h4>
            <p className="text-sm text-gray-400">Complete AI-generated exercises</p>
          </div>

          <div className="text-center">
            <div className="gradient-pink w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4 text-white font-bold text-xl">
              4
            </div>
            <h4 className="font-semibold mb-2">Get Results</h4>
            <p className="text-sm text-gray-400">Instant grading and PDF download</p>
          </div>
        </div>
      </section>

      {/* Pricing Preview */}
      <section className="text-center">
        <h2 className="mb-6 text-gradient">Simple, Transparent Pricing</h2>

        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto mb-8">
          <div className="card">
            <h3 className="mb-4">Free Trial</h3>
            <div className="text-4xl font-bold mb-4 text-gradient">$0</div>
            <ul className="text-left space-y-2 mb-6">
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>3 Grammar Tests</span>
              </li>
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>3 Vocabulary Card Sets</span>
              </li>
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>All CEFR Levels</span>
              </li>
            </ul>
            <Link href="/levels" className="btn-primary w-full block text-center">
              Start Free Trial
            </Link>
          </div>

          <div className="card border-2 border-purple-500">
            <div className="gradient-pink text-white text-sm font-bold py-1 px-4 rounded-full inline-block mb-4">
              BEST VALUE
            </div>
            <h3 className="mb-4">Yearly Subscription</h3>
            <div className="text-4xl font-bold mb-1 text-gradient">$80</div>
            <div className="text-sm text-gray-400 mb-4">$6.67/month - Save 33%</div>
            <ul className="text-left space-y-2 mb-6">
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>Unlimited Exercises</span>
              </li>
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>All Exercise Types</span>
              </li>
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>PDF Downloads</span>
              </li>
              <li className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-green-400" />
                <span>Priority Support</span>
              </li>
            </ul>
            <Link href="/subscribe" className="btn-primary w-full block text-center">
              Subscribe Now
            </Link>
          </div>
        </div>

        <p className="text-gray-400">
          Monthly plan also available for $10/month
        </p>
      </section>
    </div>
  )
}
